/** Declaration file generated by dts-gen */

export function algorithm(searchLowerCodes: any, prepared: any, searchLowerCode: any): any;

export function algorithmNoTypo(searchLowerCodes: any, prepared: any, searchLowerCode: any): any;

export function cleanup(): void;

export function getPrepared(target: any): any;

export function getPreparedSearch(search: any): any;

export function go(search: any, targets: any, options: any): any;

export function goAsync(search: any, targets: any, options: any): any;

export function highlight(result: any, hOpen: any, hClose: any): any;

export function prepare(target: any): any;

export function prepareBeginningIndexes(target: any): any;

export function prepareLowerCodes(str: any): any;

export function prepareNextBeginningIndexes(target: any): any;

export function prepareSearch(search: any): any;

export function prepareSlow(target: any): any;

export function single(search: any, target: any, options: any): any;

export namespace algorithm {
    const prototype: {
    };

}

export namespace algorithmNoTypo {
    const prototype: {
    };

}

export namespace cleanup {
    const prototype: {
    };

}

export namespace getPrepared {
    const prototype: {
    };

}

export namespace getPreparedSearch {
    const prototype: {
    };

}

export namespace go {
    const prototype: {
    };

}

export namespace goAsync {
    const prototype: {
    };

}

export namespace highlight {
    const prototype: {
    };

}

export namespace prepare {
    const prototype: {
    };

}

export namespace prepareBeginningIndexes {
    const prototype: {
    };

}

export namespace prepareLowerCodes {
    const prototype: {
    };

}

export namespace prepareNextBeginningIndexes {
    const prototype: {
    };

}

export namespace prepareSearch {
    const prototype: {
    };

}

export namespace prepareSlow {
    const prototype: {
    };

}

export namespace single {
    const prototype: {
    };

}

